---
version: '3.8'

services:
  memes:
    build: .
    healthcheck:
      test: ["CMD", "curl",
        "http://127.0.0.1:11707/up",
        ]
      interval: 60s
      timeout: 1s
      retries: 5
    image: ghcr.io/yaleman/memes-api:latest
    command: ["poetry", "run", "python", "-m", "memes_api", "--host", "0.0.0.0", "--port", "11707"]
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "127.0.0.1:11707:11707"
    volumes:
      - "${HOME}/.config/memes-api.json:/root/.config/memes-api.json"
    restart: always
