name: mypy

"on":
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v5.1.1
      - name: Running type checking
        run: mise run ty
